# Generated by Django 5.2.1 on 2025-05-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercatorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precatorio_number', models.CharField(max_length=100, unique=True)),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('forum', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precatorios', to='mercatorio.creditor')),
            ],
        ),
    ]
