# Generated by Django 5.2.1 on 2025-05-19 23:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercatorio', '0002_precatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('CNH', 'CNH'), ('birth_certificate', 'Certidão de Nascimento'), ('proof_of_address', 'Comprovante de endereço')], max_length=50)),
                ('file_url', models.URLField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mercatorio.creditor')),
            ],
        ),
    ]
