# Generated by Django 5.2.1 on 2025-05-20 00:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercatorio', '0003_personaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'Estadual'), ('municipal', 'Municipal'), ('labor', 'Trabalhista')], max_length=50)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('negative', 'Negativa'), ('positive', 'Positiva'), ('invalid', 'Invalida'), ('pending', 'Pendente')], default='pending', max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='mercatorio.creditor')),
            ],
        ),
    ]
