# Generated by Django 5.2.1 on 2025-05-20 16:45

import mercatorio.utils.validate_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercatorio', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[mercatorio.utils.validate_document.validate_document_extension, mercatorio.utils.validate_document.validate_file_size]),
        ),
    ]
