# Generated by Django 5.2.1 on 2025-05-20 21:24

import mercatorio.utils.validate_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercatorio', '0005_personaldocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[mercatorio.utils.validate_document.validate_certificate_extension, mercatorio.utils.validate_document.validate_file_size]),
        ),
    ]
